name: thatch
favicon: null
layout_spectrum: 0.28952761832624674
typography_spectrum: 0.30779924988746643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.44381857523694634
  lightness: 0.10768182296305895
  saturation: 0.6154797032941133
  rhythmicContrast: 0.10726174106821418
purpose: []
