name: thatch
favicon: null
layout_spectrum: 0.76386
typography_spectrum: 0.80957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#4f8ace'
    - '#98a5ad'
    - '#313332'
    - '#525759'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
