name: thatch
favicon: null
layout_spectrum: 0.35576
typography_spectrum: 0.93435
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5491d2'
    - '#181c1d'
    - '#737778'
    - '#d1cdc2'
    - '#9ba3a6'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
